In [99]:
import pandas as pd
import numpy as np

# books data load
books = pd.read_csv('/opt/ml/data/books.csv')
books.head()

isbn                                         book_title   
0  0002005018                                       Clara Callan  \
1  0060973129                               Decision in Normandy   
2  0374157065  Flu: The Story of the Great Influenza Pandemic...   
3  0399135782                             The Kitchen God's Wife   
4  0425176428  What If?: The World's Foremost Military Histor...   

            book_author  year_of_publication                 publisher   
0  Richard Bruce Wright               2001.0     HarperFlamingo Canada  \
1          Carlo D'Este               1991.0           HarperPerennial   
2      Gina Bari Kolata               1999.0      Farrar Straus Giroux   
3               Amy Tan               1991.0          Putnam Pub Group   
4         Robert Cowley               2000.0  Berkley Publishing Group   

                                             img_url language       category   
0  http://images.amazon.com/images/P/0002005018.0...       en  ['Actresses']  \
1  http://images.amazon.com/images/P/0060973129.0...       en  ['1940-1949']   
2  http://images.amazon.com/images/P/0374157065.0...       en    ['Medical']   
3  http://images.amazon.com/images/P/0399135782.0...       en    ['Fiction']   
4  http://images.amazon.com/images/P/0425176428.0...       en    ['History']   

                                             summary   
0  In a small town in Canada, Clara Callan reluct...  \
1  Here, for the first time in paperback, is an o...   
2  Describes the great flu epidemic of 1918, an o...   
3  A Chinese immigrant who is convinced she is dy...   
4  Essays by respected military historians, inclu...   

                            img_path  
0  images/0002005018.01.THUMBZZZ.jpg  
1  images/0060973129.01.THUMBZZZ.jpg  
2  images/0374157065.01.THUMBZZZ.jpg  
3  images/0399135782.01.THUMBZZZ.jpg  
4  images/0425176428.01.THUMBZZZ.jpg

In [100]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149570 entries, 0 to 149569
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   isbn                 149570 non-null  object 
 1   book_title           149570 non-null  object 
 2   book_author          149569 non-null  object 
 3   year_of_publication  149570 non-null  float64
 4   publisher            149570 non-null  object 
 5   img_url              149570 non-null  object 
 6   language             82343 non-null   object 
 7   category             80719 non-null   object 
 8   summary              82343 non-null   object 
 9   img_path             149570 non-null  object 
dtypes: float64(1), object(9)
memory usage: 11.4+ MB


In [101]:
# isbn 처리
books['isbn'] = books['img_url'].apply(lambda x : x.split('P/')[1][:10])
books.head()

isbn                                         book_title   
0  0002005018                                       Clara Callan  \
1  0060973129                               Decision in Normandy   
2  0374157065  Flu: The Story of the Great Influenza Pandemic...   
3  0399135782                             The Kitchen God's Wife   
4  0425176428  What If?: The World's Foremost Military Histor...   

            book_author  year_of_publication                 publisher   
0  Richard Bruce Wright               2001.0     HarperFlamingo Canada  \
1          Carlo D'Este               1991.0           HarperPerennial   
2      Gina Bari Kolata               1999.0      Farrar Straus Giroux   
3               Amy Tan               1991.0          Putnam Pub Group   
4         Robert Cowley               2000.0  Berkley Publishing Group   

                                             img_url language       category   
0  http://images.amazon.com/images/P/0002005018.0...       en  ['Actresses']  \
1  http://images.amazon.com/images/P/0060973129.0...       en  ['1940-1949']   
2  http://images.amazon.com/images/P/0374157065.0...       en    ['Medical']   
3  http://images.amazon.com/images/P/0399135782.0...       en    ['Fiction']   
4  http://images.amazon.com/images/P/0425176428.0...       en    ['History']   

                                             summary   
0  In a small town in Canada, Clara Callan reluct...  \
1  Here, for the first time in paperback, is an o...   
2  Describes the great flu epidemic of 1918, an o...   
3  A Chinese immigrant who is convinced she is dy...   
4  Essays by respected military historians, inclu...   

                            img_path  
0  images/0002005018.01.THUMBZZZ.jpg  
1  images/0060973129.01.THUMBZZZ.jpg  
2  images/0374157065.01.THUMBZZZ.jpg  
3  images/0399135782.01.THUMBZZZ.jpg  
4  images/0425176428.01.THUMBZZZ.jpg

In [102]:
books[books['isbn'].str.contains('000D')]

isbn                                         book_title   
2886    B0000DAPP1  Discover Your Genius: How to Think Like Histor...  \
24710   B0000DYXID            A Kid's Guide To How to Save the Planet   
131024  B0000D9PEZ    Body in the Library, The: A Miss Marple Mystery   
146197  B0000DAOHN                                         Hard Eight   

            book_author  year_of_publication           publisher   
2886    Michael J. Gelb               2002.0       HarperCollins  \
24710     Billy Goodman               1994.0        iBooks, Inc.   
131024  Agatha Christie               1994.0        PerfectBound   
146197  Janet Evanovich               2002.0  St. Martin's Press   

                                                  img_url language category   
2886    http://images.amazon.com/images/P/B0000DAPP1.0...      NaN      NaN  \
24710   http://images.amazon.com/images/P/B0000DYXID.0...      NaN      NaN   
131024  http://images.amazon.com/images/P/B0000D9PEZ.0...      NaN      NaN   
146197  http://images.amazon.com/images/P/B0000DAOHN.0...      NaN      NaN   

       summary                           img_path  
2886       NaN  images/B0000DAPP1.01.THUMBZZZ.jpg  
24710      NaN  images/B0000DYXID.01.THUMBZZZ.jpg  
131024     NaN  images/B0000D9PEZ.01.THUMBZZZ.jpg  
146197     NaN  images/B0000DAOHN.01.THUMBZZZ.jpg

In [103]:
books["publisher2"] = books['isbn'].apply(lambda x : str(x)[2:6])

In [104]:
books.head()

isbn                                         book_title   
0  0002005018                                       Clara Callan  \
1  0060973129                               Decision in Normandy   
2  0374157065  Flu: The Story of the Great Influenza Pandemic...   
3  0399135782                             The Kitchen God's Wife   
4  0425176428  What If?: The World's Foremost Military Histor...   

            book_author  year_of_publication                 publisher   
0  Richard Bruce Wright               2001.0     HarperFlamingo Canada  \
1          Carlo D'Este               1991.0           HarperPerennial   
2      Gina Bari Kolata               1999.0      Farrar Straus Giroux   
3               Amy Tan               1991.0          Putnam Pub Group   
4         Robert Cowley               2000.0  Berkley Publishing Group   

                                             img_url language       category   
0  http://images.amazon.com/images/P/0002005018.0...       en  ['Actresses']  \
1  http://images.amazon.com/images/P/0060973129.0...       en  ['1940-1949']   
2  http://images.amazon.com/images/P/0374157065.0...       en    ['Medical']   
3  http://images.amazon.com/images/P/0399135782.0...       en    ['Fiction']   
4  http://images.amazon.com/images/P/0425176428.0...       en    ['History']   

                                             summary   
0  In a small town in Canada, Clara Callan reluct...  \
1  Here, for the first time in paperback, is an o...   
2  Describes the great flu epidemic of 1918, an o...   
3  A Chinese immigrant who is convinced she is dy...   
4  Essays by respected military historians, inclu...   

                            img_path publisher2  
0  images/0002005018.01.THUMBZZZ.jpg       0200  
1  images/0060973129.01.THUMBZZZ.jpg       6097  
2  images/0374157065.01.THUMBZZZ.jpg       7415  
3  images/0399135782.01.THUMBZZZ.jpg       9913  
4  images/0425176428.01.THUMBZZZ.jpg       2517

In [105]:
books[~ books['publisher2'].str.isdigit()]

isbn                                         book_title   
2886    B0000DAPP1  Discover Your Genius: How to Think Like Histor...  \
15104   B0000A2U93                                           Carmilla   
24710   B0000DYXID            A Kid's Guide To How to Save the Planet   
39715   B0001GMSV2                                            Find Me   
65420   B0000X8HIE  THE FIRST TARZAN OMNIBUS: Tarzan of the Apes; ...   
69705   B0000C2W5U         Femme Fatale: Famous Beauties Then and Now   
70722   B0001FZGBC                             In Her Shoes : A Novel   
77257   B0000T6KHI                                        Three Fates   
78170   B0000AA9JB                         A Darkness More Than Night   
82023   B0000AZW79                                    O Is for Outlaw   
84097   B0000C7BNG                                       Isle of Dogs   
87835   B0000VZEJQ                      Roald Dahl's Revolting Rhymes   
98925   B0000VZEH8                                         Back Roads   
99157   B0000E63CJ                                       Dreamcatcher   
114951  B0001I1KOG       New York Public Library Literature Companion   
130283  B0001FZGRQ                          The Clan of the Cave Bear   
131024  B0000D9PEZ    Body in the Library, The: A Miss Marple Mystery   
133176  B0000T6KIM                                          Faking It   
137364  B0001FZGPI                          The Bonesetter's Daughter   
146197  B0000DAOHN                                         Hard Eight   

                      book_author  year_of_publication   
2886              Michael J. Gelb               2002.0  \
15104     Joseph Sheridan Le Fanu               1994.0   
24710               Billy Goodman               1994.0   
39715             Rosie O'Donnell               2002.0   
65420        Edgar Rice Burroughs               1994.0   
69705               Serge Normant               2001.0   
70722             Jennifer Weiner               2002.0   
77257                Nora Roberts               2002.0   
78170            Michael Connelly               2001.0   
82023                 Sue Grafton               1999.0   
84097   Patricia Daniels Cornwell               2001.0   
87835                  Roald Dahl               2002.0   
98925                Tawni O'Dell               2000.0   
99157                Stephen King               2001.0   
114951    New York Public Library               2001.0   
130283               Jean M. Auel               2001.0   
131024            Agatha Christie               1994.0   
133176            Jennifer Crusie               2002.0   
137364                    Amy Tan               2001.0   
146197            Janet Evanovich               2002.0   

                            publisher   
2886                    HarperCollins  \
15104               Soft Editions Ltd   
24710                    iBooks, Inc.   
39715                    Warner Books   
65420                      PageTurner   
69705                    Viking Press   
70722                     Atria Books   
77257                Putnam Pub Group   
78170          Little Brown & Company   
82023      Henry Holt & Company, Inc.   
84097                Putnam Pub Group   
87835   Knopf Books for Young Readers   
98925                    Viking Press   
99157                        Scribner   
114951                     Free Press   
130283         Crown Publishing Group   
131024                   PerfectBound   
133176             St. Martin's Press   
137364               Putnam Pub Group   
146197             St. Martin's Press   

                                                  img_url language category   
2886    http://images.amazon.com/images/P/B0000DAPP1.0...      NaN      NaN  \
15104   http://images.amazon.com/images/P/B0000A2U93.0...      NaN      NaN   
24710   http://images.amazon.com/images/P/B0000DYXID.0...      NaN      NaN   
39715   http://images.amazon.com/images/P/B0001GMSV2.0...      NaN      NaN   
6542

In [106]:
books[books['publisher'].str.contains('PerfectBound')]

isbn                                         book_title   
29467   B00006CRTE  Devil Knows You're Dead, The: A Matthew Scudde...  \
49188   0060913010                                    Rumors of Peace   
119650  B00019U4II                                      Big Four, The   
131024  B0000D9PEZ    Body in the Library, The: A Miss Marple Mystery   

            book_author  year_of_publication     publisher   
29467    Lawrence Block               1994.0  PerfectBound  \
49188     Ella Leffland               1985.0  PerfectBound   
119650  Agatha Christie               1994.0  PerfectBound   
131024  Agatha Christie               1994.0  PerfectBound   

                                                  img_url language category   
29467   http://images.amazon.com/images/P/B00006CRTE.0...      NaN      NaN  \
49188   http://images.amazon.com/images/P/0060913010.0...      NaN      NaN   
119650  http://images.amazon.com/images/P/B00019U4II.0...      NaN      NaN   
131024  http://images.amazon.com/images/P/B0000D9PEZ.0...      NaN      NaN   

       summary                           img_path publisher2  
29467      NaN  images/B00006CRTE.01.THUMBZZZ.jpg       0006  
49188      NaN  images/0060913010.01.THUMBZZZ.jpg       6091  
119650     NaN  images/B00019U4II.01.THUMBZZZ.jpg       0019  
131024     NaN  images/B0000D9PEZ.01.THUMBZZZ.jpg       000D

In [107]:
# drop이 필요한 것은 drop하자.
books.drop(columns=['summary','img_url','year_of_publication','img_path', 'publisher2'], inplace=True)
books.head()

isbn                                         book_title   
0  0002005018                                       Clara Callan  \
1  0060973129                               Decision in Normandy   
2  0374157065  Flu: The Story of the Great Influenza Pandemic...   
3  0399135782                             The Kitchen God's Wife   
4  0425176428  What If?: The World's Foremost Military Histor...   

            book_author                 publisher language       category  
0  Richard Bruce Wright     HarperFlamingo Canada       en  ['Actresses']  
1          Carlo D'Este           HarperPerennial       en  ['1940-1949']  
2      Gina Bari Kolata      Farrar Straus Giroux       en    ['Medical']  
3               Amy Tan          Putnam Pub Group       en    ['Fiction']  
4         Robert Cowley  Berkley Publishing Group       en    ['History']

In [108]:
import re
books.loc[books[books['category'].notnull()].index, 'category'] = books[books['category'].notnull()]['category'].apply(lambda x: re.sub('[\W_]+',' ',x).strip())

In [109]:
books['category'] = books['category'].str.lower()

In [110]:
books['category'].unique()

array(['actresses', '1940 1949', 'medical', ..., 'deafness',
       'alternative histories',
       'authors canadian english 20th century biography'], dtype=object)

## label encoding

In [14]:
# category => vectorization
categoryids = books['category'].unique()
idx2category = {idx : category_ for idx, category_ in enumerate(categoryids)}
category2idx = {category_ : idx for idx,category_ in idx2category.items()} 

In [15]:
books['category'] = books['category'].map(category2idx, na_action='ignore')
books.head()

isbn                                         book_title   
0  0002005018                                       Clara Callan  \
1  0060973129                               Decision in Normandy   
2  0374157065  Flu: The Story of the Great Influenza Pandemic...   
3  0399135782                             The Kitchen God's Wife   
4  0425176428  What If?: The World's Foremost Military Histor...   

            book_author                 publisher language  category  
0  Richard Bruce Wright     HarperFlamingo Canada       en       0.0  
1          Carlo D'Este           HarperPerennial       en       1.0  
2      Gina Bari Kolata      Farrar Straus Giroux       en       2.0  
3               Amy Tan          Putnam Pub Group       en       3.0  
4         Robert Cowley  Berkley Publishing Group       en       4.0

In [16]:
# category => vectorization
languages = books['language'].unique()
idx2languages = {idx : language_ for idx, language_ in enumerate(languages)}
language2idx = {language_ : idx for idx,language_ in idx2languages.items()} 

In [17]:
books['language'] = books['language'].map(language2idx, na_action='ignore')
books.head()

isbn                                         book_title   
0  0002005018                                       Clara Callan  \
1  0060973129                               Decision in Normandy   
2  0374157065  Flu: The Story of the Great Influenza Pandemic...   
3  0399135782                             The Kitchen God's Wife   
4  0425176428  What If?: The World's Foremost Military Histor...   

            book_author                 publisher  language  category  
0  Richard Bruce Wright     HarperFlamingo Canada       0.0       0.0  
1          Carlo D'Este           HarperPerennial       0.0       1.0  
2      Gina Bari Kolata      Farrar Straus Giroux       0.0       2.0  
3               Amy Tan          Putnam Pub Group       0.0       3.0  
4         Robert Cowley  Berkley Publishing Group       0.0       4.0

In [18]:
# category => vectorization
book_titles = books['book_title'].unique()
idx2book_titles = {idx : book_title_ for idx, book_title_ in enumerate(book_titles)}
book_title2idx = {book_title_ : idx for idx,book_title_ in idx2book_titles.items()} 

In [19]:
books['book_title'] = books['book_title'].map(book_title2idx, na_action='ignore')
books.head()

isbn  book_title           book_author                 publisher   
0  0002005018           0  Richard Bruce Wright     HarperFlamingo Canada  \
1  0060973129           1          Carlo D'Este           HarperPerennial   
2  0374157065           2      Gina Bari Kolata      Farrar Straus Giroux   
3  0399135782           3               Amy Tan          Putnam Pub Group   
4  0425176428           4         Robert Cowley  Berkley Publishing Group   

   language  category  
0       0.0       0.0  
1       0.0       1.0  
2       0.0       2.0  
3       0.0       3.0  
4       0.0       4.0

In [20]:
isbns = books['isbn'].unique()
idx2isbns = {idx : isbn_ for idx, isbn_ in enumerate(isbns)}
isbn2idx = {isbn_ : idx for idx,isbn_ in idx2isbns.items()} 

In [21]:
books['isbn'] = books['isbn'].map(isbn2idx, na_action='ignore')
books.head()

isbn  book_title           book_author                 publisher  language   
0     0           0  Richard Bruce Wright     HarperFlamingo Canada       0.0  \
1     1           1          Carlo D'Este           HarperPerennial       0.0   
2     2           2      Gina Bari Kolata      Farrar Straus Giroux       0.0   
3     3           3               Amy Tan          Putnam Pub Group       0.0   
4     4           4         Robert Cowley  Berkley Publishing Group       0.0   

   category  
0       0.0  
1       1.0  
2       2.0  
3       3.0  
4       4.0

In [22]:
books.head()

isbn  book_title           book_author                 publisher  language   
0     0           0  Richard Bruce Wright     HarperFlamingo Canada       0.0  \
1     1           1          Carlo D'Este           HarperPerennial       0.0   
2     2           2      Gina Bari Kolata      Farrar Straus Giroux       0.0   
3     3           3               Amy Tan          Putnam Pub Group       0.0   
4     4           4         Robert Cowley  Berkley Publishing Group       0.0   

   category  
0       0.0  
1       1.0  
2       2.0  
3       3.0  
4       4.0

In [23]:
books.isna().sum()

isbn               0
book_title         0
book_author        1
publisher          0
language       67227
category       68851
dtype: int64

In [24]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149570 entries, 0 to 149569
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   isbn         149570 non-null  int64  
 1   book_title   149570 non-null  int64  
 2   book_author  149569 non-null  object 
 3   publisher    149570 non-null  object 
 4   language     82343 non-null   float64
 5   category     80719 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 6.8+ MB


In [25]:
book_authors = books['book_author'].unique()
idx2book_authors = {idx : book_author_ for idx, book_author_ in enumerate(book_authors)}
book_author2idx = {book_author_ : idx for idx,book_author_ in idx2book_authors.items()} 
books['book_author'] = books['book_author'].map(book_author2idx, na_action='ignore')
books.head()

isbn  book_title  book_author                 publisher  language  category
0     0           0          0.0     HarperFlamingo Canada       0.0       0.0
1     1           1          1.0           HarperPerennial       0.0       1.0
2     2           2          2.0      Farrar Straus Giroux       0.0       2.0
3     3           3          3.0          Putnam Pub Group       0.0       3.0
4     4           4          4.0  Berkley Publishing Group       0.0       4.0

In [26]:
publishers = books['publisher'].unique()
idx2publishers = {idx : publisher_ for idx, publisher_ in enumerate(publishers)}
publisher2idx = {publisher_ : idx for idx,publisher_ in idx2publishers.items()} 
books['publisher'] = books['publisher'].map(publisher2idx, na_action='ignore')
books.head()

isbn  book_title  book_author  publisher  language  category
0     0           0          0.0          0       0.0       0.0
1     1           1          1.0          1       0.0       1.0
2     2           2          2.0          2       0.0       2.0
3     3           3          3.0          3       0.0       3.0
4     4           4          4.0          4       0.0       4.0

In [27]:
publisher2s = books['publisher2'].unique()
idx2publishers2 = {idx : publisher2_ for idx, publisher2_ in enumerate(publisher2s)}
publisher22idx = {publisher2_ : idx for idx,publisher2_ in idx2publishers2.items()} 
books['publisher2'] = books['publisher2'].map(publisher22idx, na_action='ignore')
books.head()

KeyError: 'publisher2'

In [ ]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149570 entries, 0 to 149569
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   isbn         149570 non-null  int64  
 1   book_title   149570 non-null  int64  
 2   book_author  149569 non-null  float64
 3   publisher    149570 non-null  int64  
 4   language     82343 non-null   float64
 5   category     80719 non-null   float64
 6   publisher2   149570 non-null  int64  
dtypes: float64(3), int64(4)
memory usage: 8.0 MB


## one_hot encoding

In [111]:
def one_hot_encoding(feature, feature_to_index):
    one_hot_vector = [0] * len(feature_to_index)
    index = feature_to_index[feature]
    one_hot_vector[index] = 1
    return one_hot_vector

### Category

In [112]:

df_ = pd.DataFrame(books['category'].value_counts()).reset_index()
category_df = df_[df_['count'] >= 2]
category_df

category  count
0                      fiction  33016
1             juvenile fiction   5835
2      biography autobiography   3326
3                      history   1927
4                     religion   1818
...                        ...    ...
1550       imaginary histories      2
1551        biological warfare      2
1552            animal stories      2
1553     business intelligence      2
1554  track and field athletes      2

[1555 rows x 2 columns]

In [113]:
others_list = df_[df_['count']== 1]['category'].values 
others_list

array(['35mm cameras', 'cannery row monterey calif', 'georgia', ...,
       'disguise', 'country lawyers',
       'authors canadian english 20th century biography'], dtype=object)

In [114]:
books.loc[books[books['category'].isin(others_list)].index, 'category'] = 'othres'

### language

In [115]:
language_df = pd.DataFrame(books['language'].value_counts()).reset_index()
language_df

language  count
0        en  78823
1        de   1282
2        es   1017
3        fr    883
4        it    123
5        nl     67
6        pt     47
7        da     37
8        ca     23
9        ms     10
10       no      6
11    zh-CN      3
12       ja      3
13       gl      3
14       ru      3
15       la      3
16       el      1
17       th      1
18       ro      1
19       fa      1
20       eo      1
21       gd      1
22       ga      1
23       vi      1
24    zh-TW      1
25       ko      1

In [116]:
language_df[language_df['count'] > 100]

language  count
0       en  78823
1       de   1282
2       es   1017
3       fr    883
4       it    123

In [117]:
others_list = language_df[language_df['count'] < 100]['language'].values 
others_list


array(['nl', 'pt', 'da', 'ca', 'ms', 'no', 'zh-CN', 'ja', 'gl', 'ru',
       'la', 'el', 'th', 'ro', 'fa', 'eo', 'gd', 'ga', 'vi', 'zh-TW',
       'ko'], dtype=object)

In [118]:
books.loc[books[books['language'].isin(others_list)].index, 'language'] = 'othres'

### Publisher

In [119]:
# publisher 전처리
publisher_dict=(books['publisher'].value_counts()).to_dict()
publisher_count_df= pd.DataFrame(list(publisher_dict.items()),columns = ['publisher','count'])

publisher_count_df = publisher_count_df.sort_values(by=['count'], ascending = False)

publisher_count_df

publisher  count
0                                Harlequin   3005
1                         Ballantine Books   2322
2                                   Pocket   2274
3                            Penguin Books   1943
4                             Bantam Books   1938
...                                    ...    ...
7371            Carta & the Jerusalem Post      1
7370                              Ziba Pub      1
7369   Bedford Books of St. Martin's Press      1
7368        Random House Information Group      1
11570             American Map Corporation      1

[11571 rows x 2 columns]

In [120]:

modify_list = publisher_count_df[publisher_count_df['count']>1].publisher.values
modify_list

array(['Harlequin', 'Ballantine Books', 'Pocket', ..., 'Guild Publishing',
       'Andre Deutsch', 'Peppermind'], dtype=object)

In [121]:
for publisher in modify_list:
    try:
        number = books[books['publisher']==publisher]['isbn'].apply(lambda x: x[:4]).value_counts().index[0]
        right_publisher = books[books['isbn'].apply(lambda x: x[:4])==number]['publisher'].value_counts().index[0]
        books.loc[books[books['isbn'].apply(lambda x: x[:4])==number].index,'publisher'] = right_publisher
    except: 
        pass

In [122]:
publisher_df = pd.DataFrame(books['publisher'].value_counts()).reset_index()
publisher_df

publisher  count
0                         Pocket   7306
1                      Harlequin   5268
2                   Bantam Books   4815
3             St. Martin's Press   4043
4              Vintage Books USA   3822
...                          ...    ...
1518                 Oh Editions      1
1519                        Saur      1
1520                     Rossmen      1
1521  Tascabili Economici Newton      1
1522                 Information      1

[1523 rows x 2 columns]

In [123]:
publisher_df[publisher_df['count'] > 1]

publisher  count
0                 Pocket   7306
1              Harlequin   5268
2           Bantam Books   4815
3     St. Martin's Press   4043
4      Vintage Books USA   3822
..                   ...    ...
934              Pauvert      2
935  Morgan Kaufmann Pub      2
936              Metzler      2
937                Argon      2
938              Henssel      2

[939 rows x 2 columns]

In [124]:
others_list = publisher_df[publisher_df['count'] < 2]['publisher'].values 
others_list

array(['Corbaccio', 'BD Lire /du Lys', 'C. Weise Verlag', 'P. Horay',
       'Europa-Lehrmittel', 'Kr�¶ner', 'Iwanami Shoten',
       'Katholisches Bibelwerk', 'Continental Book Company', 'Bulaaq',
       'W. Kohlhammer', 'Harpercollins (P)', 'International Books',
       'Plutonium Press', 'Marietti', 'Donence', 'Rocco', 'Manteau',
       'Un Monde diff�©rent', 'Editura Moldova',
       'Thieme Publishing Group', 'Bonnier', 'Libr. des Méridiens',
       'Picus Verlag', 'National Gallery of Australia',
       "Baha'i Distribution Service", 'Ina', 'Adnkronos libri',
       'Daimon Verlag', 'Quai Voltaire', 'Luneau Ascot', 'Garnier',
       'Xue lin chu ban she', 'Dangles', 'Labor',
       'Messidor Scand�©ditions', 'Kurtzman Sales Inc',
       'M�©dicis Entrelacs', 'H.M.S.O', 'Cadogan Books', 'Struik',
       'Reed', 'De Haan', 'Sun River Press',
       'Charles C. Thomas, Publisher Ltd', 'Nashr-i Alburz',
       'Volk und Welt', 'Envirobook', 'Halder Books', 'Anvil/PALH',
    

In [125]:
books.loc[books[books['publisher'].isin(others_list)].index, 'publisher'] = 'others'

### book_author

In [126]:
book_author_df = pd.DataFrame(books['book_author'].value_counts()).reset_index()
book_author_df

book_author  count
0              Stephen King    446
1           Agatha Christie    404
2       William Shakespeare    381
3          Barbara Cartland    283
4              Nora Roberts    241
...                     ...    ...
62053         Steven Gillis      1
62054       Robin Stevenson      1
62055           Allen Wyatt      1
62056  Merilyn Simonds Mohr      1
62057                Mapsco      1

[62058 rows x 2 columns]

In [127]:
book_author_df[book_author_df['count'] > 5]

book_author  count
0            Stephen King    446
1         Agatha Christie    404
2     William Shakespeare    381
3        Barbara Cartland    283
4            Nora Roberts    241
...                   ...    ...
4249           Dee Holmes      6
4250     Elizabeth August      6
4251    Edward R Emberley      6
4252         Melissa Bank      6
4253       Emilio Salgari      6

[4254 rows x 2 columns]

In [128]:
others_list = book_author_df[book_author_df['count'] < 6]['book_author'].values 
others_list

array(['Wanda Owen', 'Kathy Jones', 'George Sand', ..., 'Allen Wyatt',
       'Merilyn Simonds Mohr', 'Mapsco'], dtype=object)

In [129]:
books.loc[books[books['book_author'].isin(others_list)].index, 'book_author'] = 'othres'

### book_title

In [130]:
book_title_df = pd.DataFrame(books['book_title'].value_counts()).reset_index()
book_title_df[book_title_df['count']>2]

book_title  count
0                         The Secret Garden     18
1                            Selected Poems     16
2            Adventures of Huckleberry Finn     15
3                                   Dracula     15
4                                   Beloved     14
...                                     ...    ...
2324                              Katherine      3
2325                  Eyewitness to History      3
2326                           Shadowmancer      3
2327                            The Dawning      3
2328  Anne Frank: The Diary of a Young Girl      3

[2329 rows x 2 columns]

In [131]:
others_list = book_title_df[book_title_df['count'] < 3]['book_title'].values 
others_list

array(['Little Miss Stoneybrook and Dawn (Baby-Sitters Club (Paperback))',
       'Metes and Bounds (Southern Tier)',
       'Eine verh�¤ngnisvolle Wahrheit.', ...,
       'LEGACY OF HEOROT : LEGACY OF HEOROT',
       'Born On the Fourth of July',
       'Dallas Street Map Guide and Directory, 2000 Edition'],
      dtype=object)

In [132]:
books.loc[books[books['book_title'].isin(others_list)].index, 'book_title'] = 'othres'

In [133]:
one_hot_df = pd.get_dummies(books, columns=['category', 'language','book_title','book_author','publisher'], dtype=np.int8)

In [134]:
books_cp = books.copy()

In [35]:
books[books['book_author'] == 'Stephen King']

isbn                                 book_title   book_author   
118     0671042858              The Girl Who Loved Tom Gordon  Stephen King  \
246     0451162072                               Pet Sematary  Stephen King   
419     0451137965                                    Thinner  Stephen King   
420     0451150244                               Pet Sematary  Stephen King   
421     0451167317                              The Dark Half  Stephen King   
...            ...                                        ...           ...   
145209  555053150X                                  Christine  Stephen King   
146015  2290051578                                     othres  Stephen King   
146110  8484504794                                     othres  Stephen King   
147163  0671047213  The Green Mile: The Complete Serial Novel  Stephen King   
149100  0929480384                                     othres  Stephen King   

              publisher language category  
118              Pocket      NaN      NaN  
246         Signet Book       en  fiction  
419         Signet Book       en  fiction  
420         Signet Book       en  animals  
421         Signet Book       en  fiction  
...                 ...      ...      ...  
145209        Not Avail      NaN      NaN  
146015          J'ai lu      NaN      NaN  
146110       Debols!llo       en  fiction  
147163           Pocket      NaN      NaN  
149100  Books of Wonder      NaN      NaN  

[446 rows x 6 columns]

## Train & Prediction

In [135]:
train_df = books[(books['book_author'].notnull()) & (books['category'].notnull()) & (books['language'].notnull())]
train_df.head()

isbn book_title book_author                 publisher language   
0  0002005018     othres      othres                   Collins       en  \
1  0060973129     othres      othres                 Perennial       en   
2  0374157065     othres      othres      Farrar Straus Giroux       en   
3  0399135782     othres     Amy Tan          Putnam Pub Group       en   
4  0425176428     othres      othres  Berkley Publishing Group       en   

    category  
0  actresses  
1     othres  
2    medical  
3    fiction  
4    history

In [63]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 80719 entries, 0 to 149568
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   isbn         80719 non-null  object
 1   book_title   80719 non-null  object
 2   book_author  80719 non-null  object
 3   publisher    80719 non-null  object
 4   language     80719 non-null  object
 5   category     80719 non-null  object
dtypes: object(6)
memory usage: 4.3+ MB


In [136]:
isbn_list_test_not = train_df['isbn'].values
test_df = books[~books['isbn'].isin(isbn_list_test_not)]

isbn_list_test = test_df['isbn'].values

valid_df = train_df.sample(frac=0.1)
isbn_list_valid = valid_df['isbn'].values
train_df = train_df[~ train_df['isbn'].isin(isbn_list_valid)]
isbn_list_train = train_df['isbn'].values


In [43]:
len(test_df)

68851

In [159]:
train = one_hot_df[one_hot_df['isbn'].isin(isbn_list_train)]
test = one_hot_df[one_hot_df['isbn'].isin(isbn_list_test)]
valid = one_hot_df[one_hot_df['isbn'].isin(isbn_list_valid)]

train = train.set_index('isbn')
test = test.set_index('isbn')
valid = valid.set_index('isbn')

category_87th precinct imaginary place   
isbn                                                 
0060973129                                       0  \
0425176428                                       0   
074322678X                                       0   
0375759778                                       0   
0440225701                                       0   
...                                            ...   
0843932430                                       0   
3822800740                                       0   
1889613010                                       0   
0821726595                                       0   
1571741097                                       0   

            category_abandoned children  category_abbeys  category_abdomen   
isbn                                                                         
0060973129                            0                0                 0  \
0425176428                            0                0                 0   
074322678X                            0                0                 0   
0375759778                            0                0                 0   
0440225701                            0                0                 0   
...                                 ...              ...               ...   
0843932430                            0                0                 0   
3822800740                            0                0                 0   
1889613010                            0                0                 0   
0821726595                            0                0                 0   
1571741097                            0                0                 0   

            category_abduction  category_ability   
isbn                                               
0060973129                   0                 0  \
0425176428                   0                 0   
074322678X                   0                 0   
0375759778                   0                 0   
0440225701                   0                 0   
...                        ...               ...   
0843932430                   0                 0   
3822800740                   0                 0   
1889613010                   0                 0   
0821726595                   0                 0   
1571741097                   0                 0   

            category_aboriginal australians  category_abortion   
isbn                                                             
0060973129                                0                  0  \
0425176428                                0                  0   
074322678X                                0                  0   
0375759778                                0                  0   
0440225701                                0                  0   
...                                     ...                ...   
0843932430                                0                  0   
3822800740                                0                  0   
1889613010                                0                  0   
0821726595                                0                  0   
1571741097                                0                  0   

            category_absence and presumption of death   
isbn                                                    
0060973129                                          0  \
0425176428                                          0   
074322678X                                          0   
0375759778                                          0   
0440225701                                          0   
...                                               ...   
0843932430                                          0   
3822800740                                          0   
1889613010                                          0   
0821726595                                          0   
1571741097                                          0   

            cate

In [141]:
books_cp.loc[books_cp[books_cp['isbn'].isin(isbn_list_valid)].index, 'category'] = np.nan

In [143]:
one_hot_df_cp = pd.get_dummies(books_cp, columns=['category', 'language','book_title','book_author','publisher'], dtype=np.int8)

In [155]:
# set_ = set(one_hot_df.columns[one_hot_df.columns.str.contains('category')])
# len(set_)
# set_cp = set(one_hot_df_cp.columns[one_hot_df_cp.columns.str.contains('category')])
category_columns_list = list(one_hot_df.columns[one_hot_df.columns.str.contains('category')])

one_hot_df_cp = one_hot_df.copy()



In [160]:
valid_nan = valid.copy()

In [161]:
for category_ in category_columns_list:
    valid_nan[category_] = 0

In [162]:
valid_nan

category_87th precinct imaginary place   
isbn                                                 
0060973129                                       0  \
0425176428                                       0   
074322678X                                       0   
0375759778                                       0   
0440225701                                       0   
...                                            ...   
0843932430                                       0   
3822800740                                       0   
1889613010                                       0   
0821726595                                       0   
1571741097                                       0   

            category_abandoned children  category_abbeys  category_abdomen   
isbn                                                                         
0060973129                            0                0                 0  \
0425176428                            0                0                 0   
074322678X                            0                0                 0   
0375759778                            0                0                 0   
0440225701                            0                0                 0   
...                                 ...              ...               ...   
0843932430                            0                0                 0   
3822800740                            0                0                 0   
1889613010                            0                0                 0   
0821726595                            0                0                 0   
1571741097                            0                0                 0   

            category_abduction  category_ability   
isbn                                               
0060973129                   0                 0  \
0425176428                   0                 0   
074322678X                   0                 0   
0375759778                   0                 0   
0440225701                   0                 0   
...                        ...               ...   
0843932430                   0                 0   
3822800740                   0                 0   
1889613010                   0                 0   
0821726595                   0                 0   
1571741097                   0                 0   

            category_aboriginal australians  category_abortion   
isbn                                                             
0060973129                                0                  0  \
0425176428                                0                  0   
074322678X                                0                  0   
0375759778                                0                  0   
0440225701                                0                  0   
...                                     ...                ...   
0843932430                                0                  0   
3822800740                                0                  0   
1889613010                                0                  0   
0821726595                                0                  0   
1571741097                                0                  0   

            category_absence and presumption of death   
isbn                                                    
0060973129                                          0  \
0425176428                                          0   
074322678X                                          0   
0375759778                                          0   
0440225701                                          0   
...                                               ...   
0843932430                                          0   
3822800740                                          0   
1889613010                                          0   
0821726595                                          0   
1571741097                                          0   

            cate

In [55]:
len(train) + len(test)

141498

In [173]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

class AutoEncoder(nn.Module):
    def __init__(self, input_size, hidden_sizes, dropout=0.1):
        super(AutoEncoder,self).__init__()
        self.e_layers = []
        self.d_layers = []
        decoder_out_size = input_size
        
        for hidden in hidden_sizes:
            self.e_layers.append(torch.nn.Linear(input_size, hidden))
            self.e_layers.append(torch.nn.ReLU())
            self.e_layers.append(torch.nn.Dropout(p=dropout))
            input_size = hidden
        
        hidden_sizes = list(reversed(hidden_sizes))
        input_size = hidden_sizes[0]
        hidden_sizes.append(decoder_out_size)

        for hidden in hidden_sizes[1:]:
            self.d_layers.append(torch.nn.Linear(input_size, hidden))
            self.d_layers.append(torch.nn.ReLU())
            self.d_layers.append(torch.nn.Dropout(p=dropout))
            input_size = hidden   
        


        self.encoder = nn.Sequential(*self.e_layers)
        self.decoder = nn.Sequential(*self.d_layers)
        self._init_weights()
    
    def _init_weights(self):
        for module_ in self.modules():
            if isinstance(module_, nn.Linear):
                torch.nn.init.xavier_normal_(module_.weight)
    
    def forward(self,x):
        # print(x)
        x = self.encoder(x)
        # x = torch.sigmoid(x)
        x = self.decoder(x)
        # x = torch.sigmoid(x)
        return x
    

    

In [174]:
class AutoEncoder_loss_fn(nn.Module):
    """
    AutoRec_loss_fn
    
    Args:
        - loss_fn: (nn.Module) 사용할 Loss Function
    Shape:
        - Input1: (torch.Tensor) Model의 예측 결과. Shape: (batch size,)
        - Input2: (torch.Tensor) 정답. Shape: (batch size,)
        - Output: (torch.Tensor) Observable한 데이터에 대해서만 계산한 Loss. Shape: ()
    """
    def __init__(self, loss_fn):
        super(AutoEncoder_loss_fn, self).__init__()
        self.loss_fn = loss_fn
    
    def forward(self, pred, y):
        y_for_compute = y.clone().to('cpu')
        index = np.where(y_for_compute != 0) # FILL HERE : USE np.where & y_for_compute. WARNING: y를 사용 시, y의 device가 gpu일 경우 오류 발생 #
        loss = self.loss_fn(pred[index], y[index])
        return loss

In [182]:
# hyperparameter

input_size = len(train.columns)
hidden_sizes = [2048,1024,256]
lr = 0.001
epochs = 100
batch_size = 512
print(input_size)


9087


In [183]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [184]:
model = AutoEncoder(input_size=input_size,hidden_sizes=hidden_sizes).to(device)
fn_loss = AutoEncoder_loss_fn(nn.MSELoss().to(device)).to(device)
optimizer = optim.Adam(model.parameters(model.parameters()), lr=lr, amsgrad=True)

In [185]:
train_dataset = TensorDataset(torch.FloatTensor(np.array(train)))
valid_dataset = TensorDataset(torch.FloatTensor(np.array(valid)), torch.FloatTensor(np.array(valid_nan)))
test_dataset = TensorDataset(torch.FloatTensor(np.array(test)), torch.FloatTensor(np.array(test)))

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
valid_loader = DataLoader(valid_dataset, batch_size=1, shuffle=False )
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)


In [179]:
print(train_dataset[0])

(tensor([0., 0., 0.,  ..., 0., 0., 0.]),)


In [180]:
import os
import time


def make_dir(path):
        '''
        [description]
        경로가 존재하지 않을 경우 해당 경로를 생성하며, 존재할 경우 pass를 하는 함수입니다.

        [arguments]
        path : 경로

        [return]
        path : 경로
        '''
        
        if not os.path.exists(path):
            os.makedirs(path)
        else:
            pass
        return path

In [ ]:
save_path+f'{+1}.pth'

In [188]:
import datetime
import time
now = time.localtime()
now_date = time.strftime('%Y%m%d', now)
now_hour = time.strftime('%X', now)
save_time = now_date + '_' + now_hour.replace(':', '')


save_path = make_dir(f'./{save_time}/')

for epoch in range(epochs):
    running_loss = 0.0
    for data in train_loader:
        # print(data[0].size())
        data = data[0].to(device)
        optimizer.zero_grad()
        # data = torch.stack(data).to(device)
        # data = data.to(device)
        recon = model(data)
        loss_ = fn_loss(recon, data)
        loss_.backward()
        optimizer.step()
        running_loss += loss_.item()
    if (epoch < 100 and epoch % 10 == 9) or epoch % 100 == 99:
        print('[Epoch %d] loss: %.10f' % (epoch + 1, running_loss / len(train_loader)))
    if epoch % 10 == 9:
        torch.save(model, save_path+f'epoch_{epoch+1}.pth')

[Epoch 10] loss: 0.1325467347
[Epoch 20] loss: 0.1332021513
[Epoch 30] loss: 0.1338449071
[Epoch 40] loss: 0.1339520957
[Epoch 50] loss: 0.1332511030
[Epoch 60] loss: 0.1326605439
[Epoch 70] loss: 0.1332425630
[Epoch 80] loss: 0.1341203904
[Epoch 90] loss: 0.1335931292
[Epoch 100] loss: 0.1338196089


In [190]:
model = torch.load('/opt/ml/project/20230419_052807/epoch_100.pth')

loss_sum=0
k = 0
list_ = []
with torch.no_grad():
    for label, data in valid_loader:
        print(data.shape)
        print(label.shape)
        data = data.to(device).squeeze()
        #print(data)
        label = label.to(device).squeeze()
        #optimizer.zero_grad()
        # data = torch.stack(data).to(device)
        # data = data.to(device)
        recon = model(data)

        loss_ = fn_loss(recon, label)
        loss_sum += loss_
        print(f'loss : {loss_}')
        print(recon)
        print(label)
        list_.append(recon)

        k+= 1
        if k > 10:
            break
        

torch.Size([1, 9087])
torch.Size([1, 9087])
loss : 0.2000277042388916
tensor([0.0000, 1.0131, 0.0000,  ..., 0.0000, 0.0080, 0.9819], device='cuda:0')
tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')
torch.Size([1, 9087])
torch.Size([1, 9087])
loss : 0.20012204349040985
tensor([0.0000, 1.0192, 0.0000,  ..., 0.0000, 0.0110, 1.0050], device='cuda:0')
tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')
torch.Size([1, 9087])
torch.Size([1, 9087])
loss : 0.2006153166294098
tensor([0.0000, 1.0279, 0.0000,  ..., 0.0000, 0.0037, 1.0232], device='cuda:0')
tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')
torch.Size([1, 9087])
torch.Size([1, 9087])
loss : 1.9565699403756298e-05
tensor([0.0000, 1.0121, 0.0000,  ..., 0.0000, 0.0148, 0.9914], device='cuda:0')
tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')
torch.Size([1, 9087])
torch.Size([1, 9087])
loss : 0.2002139538526535
tensor([0.0000, 0.9880, 0.0000,  ..., 0.0000, 0.0236, 0.9815], device='cuda:0')
tensor([0., 0., 0.,  

In [189]:
len_ = len(category_columns_list)
for i in range(len(list_)):
    list_[i][:len_]

NameError: name 'list_' is not defined

In [ ]:
with torch.no_grad():
    for data in test_loader:
        # print(data[0].size())
        data = data[0].to(device)
        # data = torch.stack(data).to(device)
        # data = data.to(device)
        recon = model(data)

        
        break

tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]])


isbn  book_title  book_author  publisher  language  category  publisher2
0   NaN         NaN          NaN        NaN       NaN       NaN         NaN
1   NaN         NaN          NaN        NaN       NaN       NaN         NaN
2   NaN         NaN          NaN        NaN       NaN       NaN         NaN
3   NaN         NaN          NaN        NaN       NaN       NaN         NaN
4   NaN         NaN          NaN        NaN       NaN       NaN         NaN

In [ ]:
# 결측값에 대해서만 예측값 선택
imputed_values = []
for i in range(len(books)):
    if books.iloc[i].isnull().any():
        imputed_values.append(imputed_data[i])
    else:
        imputed_values.append(books.iloc[i].values)
imputed_values = np.asarray(imputed_values)

IndexError: index 68854 is out of bounds for axis 0 with size 68851